可配置化资源位置功能
lomirus/gtk-qq pull request #20
Opened 2022-06-18 03:21 UTC by Goodjooy

集中资源文件、文件夹路径加载相关接口，增加可维护性和可扩展性

- [ ] 在 `~/.gtk-qq` 下最少保留 `config.toml` 文件
  - [ ] 可配置 `Avatar` 位置
  - [ ] 可配置数据库文件位置
  - [ ] 功能更多的配置选项 
- [ ] 统一路径加载接口，而不是`dirs` 遍地开花
- [ ] 支持配置文件重新加载
- [ ] 支持根据新配置信息搬运原有数据
- [ ] 默认配置信息支持

2022-06-18 15:08 UTC, Goodjooy commented on src/app/login/service.rs
> +                Ok(path) => path,
更换成异步版本

2022-06-18 15:09 UTC, Goodjooy commented
template 默认是放系统tamplate 还是和其他资源放在一起？

2022-06-18 17:46 UTC, lomirus commented
为什么 resource-loader 的 async-ops 要作为一个 feature？作为 gtk-qq 的依赖的话，使用异步还是同步不应该是确定的吗

2022-06-18 17:52 UTC, lomirus commented
> template 默认是放系统tamplate 还是和其他资源放在一起？

你的模板目录是用来做什么的，我没太懂

2022-06-19 02:32 UTC, Goodjooy commented
> > template 默认是放系统tamplate 还是和其他资源放在一起？
> 
> 你的模板目录是用来做什么的，我没太懂

这是临时文件（）

2022-06-19 02:34 UTC, Goodjooy commented
> 为什么 resource-loader 的 async-ops 要作为一个 feature？作为 gtk-qq 的依赖的话，使用异步还是同步不应该是确定的吗

但是你原有代码里面就是同步和异步混合使用的

2022-06-19 04:04 UTC, lomirus commented
template 是模板，temporary 才是临时（

Sent from Proton Mail mobile

-------- Original Message --------
On Jun 19, 2022, 10:33 AM, 凊弦凝绝 wrote:

>>> template 默认是放系统tamplate 还是和其他资源放在一起？
>>
>> 你的模板目录是用来做什么的，我没太懂
>
> 这是临时文件（）
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/lomirus/gtk-qq/pull/20#issuecomment-1159603569), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AFBRNRCV5YAIVCFXEQTJTSLVP2BGDANCNFSM5ZEB5IJA).
> You are receiving this because you commented.Message ID: ***@***.***>

2022-06-19 04:11 UTC, lomirus commented
即使是混用，我觉得也没有也没有用 feature 的必要（因为 feature 开不开启是确定的），作为一个普通的模块就可以了。

当然，关于混用的问题最好还是统一下。可能是之前有的函数使用异步的话不方便在 relm4 的方法中调用，所以我就没统一。

Sent from Proton Mail mobile

-------- Original Message --------
On Jun 19, 2022, 10:34 AM, 凊弦凝绝 wrote:

>> 为什么 resource-loader 的 async-ops 要作为一个 feature？作为 gtk-qq 的依赖的话，使用异步还是同步不应该是确定的吗
>
> 但是你原有代码里面就是同步和异步混合使用的
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/lomirus/gtk-qq/pull/20#issuecomment-1159603689), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AFBRNRFFDXNLIEW6SOGYAMLVP2BKJANCNFSM5ZEB5IJA).
> You are receiving this because you commented.Message ID: ***@***.***>

2022-06-19 04:30 UTC, lomirus commented
临时文件的话放系统目录吧，`/tmp` 目录每次重启时系统会自动清理

2022-06-19 04:44 UTC, Goodjooy commented
临时文件配置还没想好要怎么实现，所以先用temp 临时顶替

2022-06-19 04:45 UTC, Goodjooy commented
是否需要考虑更新配置的功能？
目前配置文件是static 的全局变量

我是实现了一个可以更新的结构体，但是有个更新以后，更新前取出来的引用会变成悬垂引用的问题

2022-06-19 04:49 UTC, lomirus commented
我觉得更新配置在当前没有什么必要的使用场景，所以可以先跳过这部分

Sent from Proton Mail mobile

-------- Original Message --------
On Jun 19, 2022, 12:46 PM, 凊弦凝绝 wrote:

> 是否需要考虑更新配置的功能？
> 目前配置文件是static 的全局变量
>
> 我是实现了一个可以更新的结构体，但是有个更新以后，更新前取出来的引用会变成悬垂引用的问题
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/lomirus/gtk-qq/pull/20#issuecomment-1159616384), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AFBRNRGTCEMHNAE6EN6Q6XTVP2QZDANCNFSM5ZEB5IJA).
> You are receiving this because you commented.Message ID: ***@***.***>

2022-06-29 15:03 UTC, lomirus commented on src/main.rs
> +    resource_loader::load_from_file().expect("Failure Load Configuration");
读着总感觉有点别扭，个人建议改成 `Failed to load configuration` 或者 `Failure on loading configuration`

整个项目的日志格式也确实该统一下了，我后面有空改改（

2022-06-29 15:11 UTC, lomirus commented on libs/resource-loader/src/static_data.rs
> +//! storage static data
`storage` 是名词，建议改成 `storage of` 或调整语序

2022-06-29 15:20 UTC, Goodjooy commented on src/main.rs
> +    resource_loader::load_from_file().expect("Failure Load Configuration");
日志我是建议引入log库

2022-06-29 15:29 UTC, lomirus commented
AvatarGroup 和 AvatarUser （“头像组”和“头像用户”）感觉也有点别扭，建议调整下单词语序

2022-06-29 16:04 UTC, lomirus requested changes

2022-06-29 16:04 UTC, lomirus commented on libs/resource-loader/src/utils.rs
> +macro_rules! default_string {
这个宏只在 configs 内部用到了，建议放到模块里面（

2022-06-29 16:05 UTC, lomirus commented
我在我环境上跑报错：
```
thread 'main' panicked at 'Failure on loading configuration: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:23:38
```

2022-06-29 23:08 UTC, Goodjooy commented
> 我在我环境上跑报错：
> 
> ```
> thread 'main' panicked at 'Failure on loading configuration: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/main.rs:23:38
> stack backtrace:
>    0: rust_begin_unwind
>              at /rustc/88860d5474a32f507dde8fba8df35fd2064f11b9/library/std/src/panicking.rs:584:5
>    1: core::panicking::panic_fmt
>              at /rustc/88860d5474a32f507dde8fba8df35fd2064f11b9/library/core/src/panicking.rs:142:14
>    2: core::result::unwrap_failed
>              at /rustc/88860d5474a32f507dde8fba8df35fd2064f11b9/library/core/src/result.rs:1785:5
>    3: core::result::Result<T,E>::expect
>              at /rustc/88860d5474a32f507dde8fba8df35fd2064f11b9/library/core/src/result.rs:1035:23
>    4: gtk_qq::main::{{closure}}
>              at ./src/main.rs:23:5
>    5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
>              at /rustc/88860d5474a32f507dde8fba8df35fd2064f11b9/library/core/src/future/mod.rs:91:19
>    6: tokio::park::thread::CachedParkThread::block_on::{{closure}}
>              at /home/lomirus/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/park/thread.rs:263:54
>    7: tokio::coop::with_budget::{{closure}}
>              at /home/lomirus/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:102:9
>    8: std::thread::local::LocalKey<T>::try_with
>              at /rustc/88860d5474a32f507dde8fba8df35fd2064f11b9/library/std/src/thread/local.rs:445:16
>    9: std::thread::local::LocalKey<T>::with
>              at /rustc/88860d5474a32f507dde8fba8df35fd2064f11b9/library/std/src/thread/local.rs:421:9
>   10: tokio::coop::with_budget
>              at /home/lomirus/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:95:5
>   11: tokio::coop::budget
>              at /home/lomirus/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:72:5
>   12: tokio::park::thread::CachedParkThread::block_on
>              at /home/lomirus/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/park/thread.rs:263:31
>   13: tokio::runtime::enter::Enter::block_on
>              at /home/lomirus/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/enter.rs:151:13
>   14: tokio::runtime::thread_pool::ThreadPool::block_on
>              at /home/lomirus/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/thread_pool/mod.rs:81:9
>   15: tokio::runtime::Runtime::block_on
>              at /home/lomirus/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/mod.rs:477:43
>   16: gtk_qq::main
>              at ./src/main.rs:34:5
>   17: core::ops::function::FnOnce::call_once
>              at /rustc/88860d5474a32f507dde8fba8df35fd2064f11b9/library/core/src/ops/function.rs:248:5
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> ```

没有找到配置文件，在`~\.gtk-qq`下新建一个空白的 `config.toml` 即可

顺便一提我调整了sqlite3的那个db 文件的位置。因为考虑以后可能会有其他数据库的信息文件，所以移动到一个文件夹内部了，你可以把 app.ab 移动到 `~\.gtk-qq\database\` 文件夹内，然后改名为 `sql_db.db` (如果你没有动配置文件)

2022-06-29 23:13 UTC, Goodjooy commented on libs/resource-loader/src/ops/database.rs
> +    fn create_path() -> Option<&'static Path> {
这里不是创建，这里应该是 `path_for_create` 返回的是需要创建的路径，如果没有就是None

我接口名称改改

2022-06-29 23:17 UTC, Goodjooy commented on libs/resource-loader/src/ops/mod.rs
> +        fn get_and_do_action(action: DirAction) -> io::Result<&'static Path> {
这里原来是 3 个方法全部在 `GetPath` 里面的,后面觉得创建文件夹的操作可以独立出来，就变成这个样子了

所以实际上是 `get_path` 和 `create_and_get_path` 然后 那个action 是为了能配合 `src/util/avatar` 里面的`DirAction` 使用

2022-06-29 23:24 UTC, Goodjooy commented on libs/resource-loader/src/utils.rs
> +macro_rules! default_string {
rust 宏的作用域我一直很模糊，移动后宏的作用域我不好说

2022-06-29 23:40 UTC, Goodjooy commented on libs/resource-loader/src/ops/mod.rs
> +        fn get_and_do_action(action: DirAction) -> io::Result<&'static Path> {
将创建文件夹的操作独立出来，同时还可以提供同步与异步2套接口

2022-06-29 23:40 UTC, Goodjooy commented on libs/resource-loader/src/ops/mod.rs
> +        fn get_and_create() -> io::Result<&'static Path> {
确实，更改完成

2022-06-29 23:42 UTC, Goodjooy commented on libs/resource-loader/src/configs/avatar.rs
> +    BaseDir=>"avatars"
手动格式化完成

2022-06-30 05:09 UTC, lomirus commented
> 没有找到配置文件，在`~\.gtk-qq`下新建一个空白的 `config.toml` 即可

这里还是让程序自己创建比较好吧，不能指望每个用户都手动创建

2022-06-30 05:37 UTC, lomirus commented on libs/resource-loader/src/ops/mod.rs
> +        fn get_and_do_action(action: DirAction) -> io::Result<&'static Path> {
我还是不太理解，既然 DirAction 只有创建目录和不执行操作两种，那如果要创建并获取目录直接改成用 `create_and_get_path()`，"不执行操作"对应成不执行相关函数不就行了吗

比如下面这样，和你说的“将创建文件夹的操作独立出来，同时还可以提供同步与异步2套接口”应该是不矛盾的

```rust
pub trait SyncCreatePath: GetPath {
    fn create_and_get_path() -> io::Result<&'static Path> {
        #[cfg(feature = "logger")]
        log::debug!("create and get path {:?}", path);

        if let Some(path) = <Self as GetPath>::path_for_create() {
            create_dir_all(path)?;
        }
        Ok(<Self as GetPath>::get_path())
    }

    fn get_path() -> &'static Path {
        <Self as GetPath>::get_path()
    }
}
```

2022-06-30 05:40 UTC, lomirus commented on libs/resource-loader/src/ops/mod.rs
> +        fn get_and_do_action(action: DirAction) -> io::Result<&'static Path> {
我还是不太理解，既然 DirAction 只有创建目录和不执行操作两种，那如果要创建并获取目录直接改成用 create_and_get_path()，"不执行操作"对应成不执行相关函数不就行了吗

比如下面这样把 do_action 删掉，因为 DirAction 实际上本来就只有 `CreateAll` 一种，和你说的“将创建文件夹的操作独立出来，同时还可以提供同步与异步2套接口”应该是不矛盾的吧
```
pub trait SyncCreatePath: GetPath {
    fn create_and_get_path() -> io::Result<&'static Path> {
        #[cfg(feature = "logger")]
        log::debug!("create and get path {:?}", path);

        if let Some(path) = <Self as GetPath>::path_for_create() {
            create_dir_all(path)?;
        }
        Ok(<Self as GetPath>::get_path())
    }
}
```

2022-07-02 08:30 UTC, Goodjooy commented on libs/resource-loader/src/ops/mod.rs
> +        fn get_and_do_action(action: DirAction) -> io::Result<&'static Path> {
> 我还是不太理解，既然 DirAction 只有创建目录和不执行操作两种，那如果要创建并获取目录直接改成用 `create_and_get_path()`，"不执行操作"对应成不执行相关函数不就行了吗
> 
> 比如下面这样把 do_action 删掉，因为 DirAction 实际上本来就只有 `CreateAll` 一种，和你说的“将创建文件夹的操作独立出来，同时还可以提供同步与异步2套接口”应该是不矛盾的吧
> 
> ```rust
> pub trait SyncCreatePath: GetPath {
>     fn create_and_get_path() -> io::Result<&'static Path> {
>         #[cfg(feature = "logger")]
>         log::debug!("create and get path {:?}", path);
> 
>         if let Some(path) = <Self as GetPath>::path_for_create() {
>             create_dir_all(path)?;
>         }
>         Ok(<Self as GetPath>::get_path())
>     }
> }
> ```

这个其实是为了兼容 `src/util/avatar` 里面的操作，当时就是用的 DirAction, 现在加入日志了，你可以看看，头像加载部分全部走的是 dir action

2022-07-02 08:31 UTC, Goodjooy commented
> > 没有找到配置文件，在`~\.gtk-qq`下新建一个空白的 `config.toml` 即可
> 
> 这里还是让程序自己创建比较好吧，不能指望每个用户都手动创建

现在会自动创建配置文件了

2022-07-02 08:32 UTC, Goodjooy commented on libs/resource-loader/src/static_data.rs
> +        log::warn!("Config not set, Using Default Config");
更改好了

2022-07-02 08:34 UTC, Goodjooy commented on libs/resource-loader/src/ops/mod.rs
> +        fn get_and_do_action(action: DirAction) -> io::Result<&'static Path> {
```rust
pub trait AvatarLoader {
    fn get_avatar_location_dir(action: DirAction) -> io::Result<&'static Path>;
    fn avatar_download_url(id: i64) -> Cow<'static, String>;

    fn download_avatar(
        id: i64,
    ) -> Pin<Box<dyn Future<Output = Result<(), AvatarError>> + Send + Sync>> {
        use tokio::fs::write;

        let filename = <Self as AvatarLoader>::get_avatar_filename(id, DirAction::CreateAll);
        let url = <Self as AvatarLoader>::avatar_download_url(id);

        Box::pin(async move {
            println!("Downloading {}", url);
            let body = reqwest::get(&*url).await?.bytes().await?;

            write(filename?, &body).await?;

            Ok(())
        })
    }

    fn get_avatar_filename(id: i64, action: DirAction) -> io::Result<PathBuf> {
        <Self as AvatarLoader>::get_avatar_location_dir(action)
            .map(|p| p.join(format!("{}.png", id)))
    }

    fn get_avatar(id: i64) -> io::Result<PathBuf> {
        <Self as AvatarLoader>::get_avatar_filename(id, DirAction::None)
    }

    fn get_avatar_as_pixbuf(id: i64, width: i32, height: i32) -> Result<Pixbuf, AvatarError> {
        let path = <Self as AvatarLoader>::get_avatar(id)?;
        if !path.exists() {
            Err(io::Error::new(
                io::ErrorKind::NotFound,
                "Target Avatar Not Found",
            ))?;
        }
        let pix_buf = Pixbuf::from_file_at_size(path, width, height)?;

        Ok(pix_buf)
    }
}
```
这里在使用 dir action

2022-07-02 08:35 UTC, Goodjooy commented
我没动过的代码没法通过检查？

2022-07-02 09:06 UTC, Goodjooy commented
github action 的rust 版本固定一下吧， 最新的`clippy` 的 `needless_borrow` 目前是个傻瓜 
#https://github.com/rust-lang/rust-clippy/issues/9049

2022-07-04 08:51 UTC, Goodjooy commented on libs/resource-loader/src/ops/mod.rs
> +        fn get_and_do_action(action: DirAction) -> io::Result<&'static Path> {
我依旧觉得应当保留
---
在 `AvatarLoader` 里面，如果去除 `DirAction` 原本一个函数就需要分裂成2个
原来的`get_avatar_location_dir` 就会变成 `create_get_avatar_location_dir` 和 `get_avatar_location_dir`

2022-07-04 08:55 UTC, Goodjooy commented on libs/resource-loader/src/utils.rs
> +macro_rules! default_string {
这个宏我只有放在这个位置，然后在`lib` 里面使用 `#[marco_use]` 才能在其他位置可见

尝试移动到模块内对模块内是不可见的

2022-07-04 11:21 UTC, merged